### PR TITLE
[cookies] Added cookies

### PR DESCRIPTION
**Pull request by NakedJavaScript**
# Added Cookies to the Site

## How to test?

* Load the site
* A cookie warning should show up at the bottom of the page
* If it doesn't work try to delete the cookies for your browser

### CODE REVIEW

**Comment by WeZyBugFix** [comment]
- [ ] Is it possible to place the cookie alert above the footer? Would look better in my opinion.

**Comment by Orangenspannung** [comment]
the fuck

**Comment by Orangenspannung** [comment]
the fug

**Comment by Orangenspannung** [comment]
Looks good for me, I will merge it.

**Pull request merged**
