### PR TITLE
M64]sql code auf injections prüfen

### PR DESCRIPTION
**Pull request by Orangenspannung**
# What has changed:
* Add sanitizing function for the $_Get,$_Post forms, this should prevent MySQL injections from users.
# How to test:
* Go to any forms on our website and try to type in a valid MySQL statement, you should get an error message preventing an injection. Try this with all forms that we have.

### CODE REVIEW

**Comment by Orangenspannung** [comment]
Please test extensively because merge conflict

**Comment by NakedJavaScript** [comment]
When you type in an injection into the food add/edit form it'll redirect you to an empty site with the sql code

**Comment by NakedJavaScript** [comment]
unbenannt

**Comment by NakedJavaScript** [comment]
unbenannt

This goes on and on, please check again also @WeZyBugFix please also check

**Comment by NakedJavaScript** [comment]
Looks gewd

**Pull request merged**
