### PR TITLE
M27 essen in wochenansicht hinzufügen

### PR DESCRIPTION
**Pull request by Orangenspannung**
# What has changed:
* You can now add a day meal in the index page, be aware that the day meal doesn't get displayed (this is another ticket).
# How to test:
* Go to the index page you should see the add day meal button, click it and select a meal
* You should get a message if the adding was successful but you won't see the meal added.
* To see if a meal was added, check the database under "tagesangebot".

### CODE REVIEW

**Comment by WeZyBugFix** [comment]
- [ ] Add the function to the dependencies site, so we have all functions in one site.

- [ ] The Output should be underneath the header (check how I did it)

- [ ] When the Tagesangebot is added it should show that on page - please fix that.

- [ ] Dates are still in english. please change them to german.

- [ ] For me the date in the database is '0000-00-00'. that must be fixed too.

**Comment by NakedJavaScript** [comment]
Wezy said everything I noticed too, fix that and it's all good

**Comment by Orangenspannung** [comment]
For the tasks: The success message is now under the header but there is an ugly space between, looks like its the same on other pages so that's not nice.
Its now shown when a day has a meal attached, the details will be added to another ticket, same goes with the changing of date from English to German.
The point with the dependencies has been discussed, I will check it if is alright.
It looks like we cant change the format of the date in the database, it seems like we need to format it when fetching from the database.

Please review again.

**Comment by WeZyBugFix** [comment]
date in database is still 0000-00-00 please fix that.
please merge this ticket with the other ticket and show food after it is added.
the "hinzufügen" buttons should only be shown if adminrechte=2

**Comment by NakedJavaScript** [comment]
I created a new ticket for the space after success/error messages, other than that it works, just fix the conflicts and you can merge it

**Comment by Orangenspannung** [comment]
Julian we already talked about the display of the added food, this is another ticket, you can see it in trello.
Also, i mentioned it already twice I looked up the date problem and the only solution I found was to format it when fetching from the database. The rest should be now implemented as requested. Need to Approvements to merge.

**Pull request merged**
