### PR TITLE
M16 bearbeitung des profils ermöglichen

### PR DESCRIPTION
**Pull request by Orangenspannung**
# What has changed:
* You can now edit your profile
# How to test:
* Edit your profile in every way possible.

# To the objectives in trello:
* Instead of typing in your old password, you need to confirm your password now, I think this would cover more cases (to edit your profile you must be logged in in the first place and when you are so stupid to not log off, well without the correct email you cant go anywhere and that can be changed too).
* Yeah no, having a bad name validation can be a pain in the ass, believe me, dudes can be very creative,
suck dick to s_uck dick and so on).

### CODE REVIEW

**Comment by WeZyBugFix** [comment]
- Please inform User, when editing his profile it has to be an @its-stuttgart.de domain
if fixed than just wait for @NakedJavaScript 's review and than you can merge

**Comment by NakedJavaScript** [comment]
The E-Mail Input is broken, type in bla@bla.de and it works, wont change the Database tho, only tells you that your changes were successful

**Comment by NakedJavaScript** [comment]
I can type into the first passwort input: 123 and then in the second: abc and it still works, the second input should validate the first

**Comment by Orangenspannung** [comment]
@NakedJavaScript We talked about the error messages, having an error message for every possible combination would be a cluster fuck with the logic right now, important is, nothing breaks.

**Comment by Orangenspannung** [comment]
Just for clarification, if you have at least one valid input, you will get a success message, the invalid input won't be saved but having an accurate alert message for every possible combination would be a cluster fuck with the logic right now, important is, nothing breaks.

**Comment by Orangenspannung** [comment]
We can rework the email input field like in the benutzerliste. I can do that tomorrow.

**Comment by NakedJavaScript** [comment]
@Orangenspannung Yeah rework the email input field please, after that I'll re-review again

**Comment by Orangenspannung** [comment]
ffs, last night I fucking pushed on this branch, why doesn't my commit show up? (i did the same thing as you @WeZyBugFix)

**Pull request merged**
