### PR TITLE
M32 Essen/Nutzer bearbeiten

### PR DESCRIPTION
**Pull request by WeZyBugFix**
- When clicking the edit Button all data will be shown in the Modal.
- After pressing the "Änderungen Speichern" we get a message if update was succesfull or not.
- Also fixed the Alert Box / Modal issue.

### CODE REVIEW

**Comment by NakedJavaScript** [comment]
screen shot 2018-01-24 at 14 12 09

Why can't u change the password?

Also remove this 1Pass2Wort3-thingy, looks ugly, just use "Passwort"

**Comment by NakedJavaScript** [comment]
screen shot 2018-01-24 at 14 15 10

"Wurde" klein

Otherwise it looks good to me

**Comment by WeZyBugFix** [comment]
@Orangenspannung so the admin should be able to change the password of the User too? I left is disabled, so the update works fine, if he types nothing in there. But if you wish I can make that as required.

**Comment by NakedJavaScript** [comment]
@WeZyBugFix Well he should be able to change it, in the end he's the Admin and should have the rights to change everything ^^

**Comment by NakedJavaScript** [comment]
If I change the password it doesn't change in the DB, I still have to use the old password

Also I think you didn't understand me correct, you shouldn't make the password change required only give the admin the option to change it, but not required when changing the users balance, name or anything else

**Comment by Orangenspannung** [comment]
Found some stuff:
* The checkbox for the user for the admin rights don't display the actual rights of the user
* I can set the admin rights of myself to No, which make it possible to lock me out of the system forever, you should not have the possibility to do that.
* After adding a new food, I get a warning that a food with this name already exists, even when this is not true, the food will be added anyway
* The checkboxes in the edit modal are always unchecked, no matter what  should be
* You can click on the name of the no allergenic text, this disables all the other checkboxes but doesn't check the own checkbox.
* Why are all chars uppercase? 
* And well, there is a merge conflict.

**Comment by WeZyBugFix** [comment]
@Orangenspannung 
- will try to get that done...
- so if a Admin edits an admin he shouldn't be able to change admin rights?
- so I tried that several times now and never got that error.
- Okay will try to comma separate the string and check by value
- all chars are upper case because MySQL is case sensitive, so when i add "maultasche" but "MAULTASCHE" already exists, the food gets added anyway.
- there wasn't before the other two PR's were merged^^

**Comment by NakedJavaScript** [comment]
@WeZyBugFix No he meant that you can change your own Admin rights, which shouldn't be possible.

**Comment by WeZyBugFix** [comment]
@NakedJavaScript okay understood

**Comment by NakedJavaScript** [comment]
when I change the email of an existing user his password is changed to "ABC"? Why is that so?

**Comment by WeZyBugFix** [comment]
@NakedJavaScript fixed the issue.

**Pull request merged**
