### PR TITLE
M04   add a back to top button

### PR DESCRIPTION
**Pull request by NakedJavaScript**
Just reload the site, go to a page that has a lot of content (imprint), scroll and press the button

### CODE REVIEW

**Comment by Orangenspannung** [comment]
back to top button looks shit

**Comment by NakedJavaScript** [comment]
No. Thats fine.

Dunno how you broke it, works fine for me

**Comment by Orangenspannung** [comment]
Hmmm, we need Julian for this.

**Comment by WeZyBugFix** [comment]
button does not appear in any case for. even when I add more food and the list gets longer and longer. refreshing did not help too., dunno what could be the problem.

**Pull request merged**
