### PR TITLE
Added static Text when Creating or Editing Food/User

### PR DESCRIPTION
**Pull request by WeZyBugFix**
Static text on input Fields in the Edit/Creation Modals

### CODE REVIEW

**Comment by NakedJavaScript** [comment]
unbenannt

Please go through the whole code and remove those error messages with something human readable

**Comment by WeZyBugFix** [comment]
@NakedJavaScript @Orangenspannung There shouldn't be any bigger Errors from now on. Every error, which could appear is catched.

**Comment by NakedJavaScript** [comment]
@WeZyBugFix i still see them, did you forget commit?

**Comment by WeZyBugFix** [comment]
@Orangenspannung  In my case no issue like that.
capture

**Comment by Orangenspannung** [comment]
u_wot_m8

**Comment by NakedJavaScript** [comment]
I dont have the checkbox bug neither, so its okay for me. But there are still error messages which are not human-readable, I fixed them

**Pull request merged**
