### PR TITLE
M15 fix login

### PR DESCRIPTION
**Pull request by WeZyBugFix**
- Login funktioniert nun und nachdem man eingeloggt ist erscheint ein Dropdown menü, wo vorher der Login button war.

- Beim anlegen von Speisen/Nutzern wird vorher überprüft, ob es diese bereits gibt.

- Beim Anlegen eines users gibt es nun auch einen "pepper" beim hashen der Passworts, dies fügt immer ein extra Wort zum eingegeben Passwort hinzu. Dieser pepper ist GEHEIM zu halten.

-unnötige Dateien wurden gelöscht (delete_food.php, login.php und phpinfo.php)

- SESSION_START() steht nun in den dependencies, da es auf jeder Seite gebraucht wird.

### CODE REVIEW

**Comment by Orangenspannung** [comment]
Well, when I try to log in I get constantly the message that my password is wrong no matter if I use an old or a new account.

- [ ]  Check if other people can log in (maybe the pepper thing is broken?)

**Comment by WeZyBugFix** [comment]
@Orangenspannung I tested it and it worked fine. did you check, if you used the right database? At the 'benutzer' table the type of the 'passwort' column must be varchar(255).

**Comment by NakedJavaScript** [comment]
@Orangenspannung Works fine for me

**Comment by NakedJavaScript** [comment]
@WeZyBugFix Pls fix this:

unbenannt

**Comment by NakedJavaScript** [comment]
unbenannt

- [ ] Change the text of the Login Form. Title should just be "Login" and Password with "t", also we need a "Passwort vergessen?" Thingy, but that would be a new ticket, I'll open one at trello

**Comment by NakedJavaScript** [comment]
unbenannt

- [ ] Don't call it action, take the Users name

**Comment by NakedJavaScript** [comment]
unbenannt

- [ ] Fix that, yo

**Comment by NakedJavaScript** [comment]
Some general things:

- [ ] When clicking on the Button you should be linked to your profile
- [ ] Also clicking on Profil and Bestellungen should link you to the pages
- [ ] The Logout page looks shitty, please steal the style I used for the contact form when sending an mail

**Comment by Orangenspannung** [comment]
My bad didn't use the right database.  But found a bug:

- [ ] You can type only one word in the "Nachname Vorname" field, this breaks some stuff. Better make two different fields for two different inputs (some people have more than one name).

We need also a fixtures update when this gets merged.

**Comment by WeZyBugFix** [comment]
@Orangenspannung w discussed about this and we think it's unnecessary. also everybody is only using their first firstname and lastname anyway.

**Comment by NakedJavaScript** [comment]
I get this error:

unbenannt

**Comment by NakedJavaScript** [comment]
Also there are merge conflicts, pls fix them

**Comment by Orangenspannung** [comment]
I fixed what was mentioned and other stuff, needs to be reviewed again.

**Pull request merged**
